# Generated by Django 5.2.8 on 2025-12-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register_jzdn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Degree',
            new_name='Degree_jzdn',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_jzdn',
        ),
    ]
