# Generated by Django 5.2.8 on 2025-12-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
    ]
