# Generated by Django 5.2.8 on 2025-12-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_auto_20251215_2315'),
    ]

    operations = [
    ]
