# Generated by Django 5.2.8 on 2025-12-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0003_populate_degrees'),
    ]

    operations = [
    ]
